### ISSUE TITLE
Unable to locate Credentials 

### ISSUE THREAD

**Issue by aravindkaws** [aws-quickstart/taskcat#41] opened 2017-09-07 11:29 UTC
We have a Cloudformation template created and I am in the process of testing this using TaskCat.  Here’s the command I am using
 
taskcat -c awstaskcat/ci/config.yml -A "AKIAJXXXXXXXE6GEVXX" -S "V6k2XXXXXXXXXXXXXXXXXXXXXXXiiXX"
 
Although the Access and Secret Keys are valid, I am getting the following error message
"Unable to locate Credentials"
"Cannot launch XXXXXXXXX.template"

**Comment by zhenqing-zhang** [comment] 2017-09-30 02:21
I got the same error
if I change to another template, the taskcat worked as expected, but another template met this error.
what will cause this error? any update.

**Comment by avattathil** [comment] 2017-09-30 18:08
Can you describe the differences bewteen the templates?

I need more info to reproduce this error

**Comment by avattathil** [comment] 2017-10-02 17:40
@zhenqing-zhang when say "change templates" do you mean changed the filenames ? Can you tell me exactly what you did so I can replicate it. 
Also please paste the error message.

**Comment by nstewart** [comment] 2018-01-09 02:29
Hi -- I get this error when I try running taskcat in a region other than us-east-1

**Comment by avattathil** [comment] 2018-01-09 04:56
Can you please paste your terminal outputs. Are you using using the pip or docker version ?

**Comment by nstewart** [comment] 2018-01-10 12:06
Hi -- I'll be able to provide more info on Friday. In the meantime, I was using the docker version and for credentials, I was specifically using the -A and -S flags rather than environment variables.

**Comment by nstewart** [comment] 2018-01-14 20:33
I can't reproduce the problem because I'm seeing another error in the docker version now
`An error occurred (SignatureDoesNotMatch) when calling the ValidateTemplate operation: Signature not yet current: 20180114T203136Z is still later than 20180114T202746Z (20180114T202246Z + 5 min.)`

I switched to the python version and that seems to be working fine.

**Comment by avattathil** [comment] 2018-01-14 20:48
Thanks Nate,

Glad you got the pip version working!
This error could be due to time not being insync with the container and the
host (os time). Restarting the docker deamon should synchronize the time.

**Comment by nstewart** [comment] 2018-01-22 20:07
In case anyone else has this issue, in addition to using the python script I had to run `aws configure` (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) for some reason taskcat wasnt honoring the command line flags when I'm not in us-east-1.

**Comment by avattathil** [comment] 2018-01-22 20:22
@nstewart thanks for the update.  What were the command line argument you pass in? 

Do you mean you set the default region using `aws configure` ?

Also were you able resolve the issue after you after running `aws configure` ?

**Comment by nstewart** [comment] 2018-01-22 20:45
command: `taskcat -c <path to config> -A <pub key> -S <priv key>`

I set the default region using `aws configure` to us-west-1

I was able to resolve the issue after I ran that.

I noticed that in the taskcat python code there is a line that sets the default to us-east-1 so maybe that has something to do with some of the weirdness people are seeing. I didnt drill in from there though.

**Comment by avattathil** [comment] 2018-01-22 20:53
Great I will replicate using using these conditions and provide an update

**Comment by avattathil** [comment] 2018-03-06 08:13
Fixed in  https://github.com/aws-quickstart/taskcat/commit/da7644bbb4dc7954f834264163856fad8fd9c06d

**Closed by avattathil** 2018-03-06 08:13 UTC

**Comment by Rjt77** [comment] 2018-09-04 12:03
I tried with same configuration with region set as us-east-1 and us-west-1. However, its throwing following error:
[ERROR  ] :Credential Error - Please check you keys!
 My command is taskcat -c <path to config file> -A ACCESS_KEY -S ACCESS_SECRET_KEY
