### ISSUE TITLE
tCaT stack name prefix unusable as S3 bucket name prefix

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#271] opened 2019-03-15 10:48 UTC
The default prefix for stack names is `tCaT`, which is problematic if the someone uses the stack name as prefix for S3 bucket names because it contains uppercase characters.

**Comment by villasv** [comment] 2019-03-15 11:08
I'm very curious... why is this value hidden in a base64 string [in here](https://github.com/aws-quickstart/taskcat/blob/ac7481cfeb03003f33ec83e9d1e67cceb653d5fd/taskcat/stacker.py#L71)?
```
sig = base64.b64decode("dENhVA==").decode()
```

**Comment by avattathil** [comment] 2019-03-15 11:32
We use this as signature that allows one to know which stacks were created by taskcat regardless of the tag. It's not something we cannot currently change. As we have customers using for various types reports and clean up.

**Comment by villasv** [comment] 2019-03-15 11:34
Sure, makes sense to include a signature. But
1. Can we change it to `tcat` instead of `tCaT`?
2. Can we just write `tcat` in the source code instead of a base64 string?

**Comment by agamzn** [comment] 2019-03-15 14:30
@villasv  - We'll discuss internally early next week and circle back. Most of us are traveling today. Just an FYI - we're not ignoring!

**Comment by e14nielson** [comment] 2019-05-08 17:58
+1 i like to use the stack name as part of my bucket names.

**Comment by villasv** [comment] 2019-05-09 00:53
As an update, I ended up removing fixed bucket names from the stack. It was impossible to run parallel tests, and it's kind of a best practice to avoid bucket name collisions.

I'd still consider changing `tCaT` to `tcat` and explicitly write it in code, though, so I won't close the issue.

**Comment by andrew-glenn** [comment] 2019-07-22 15:31
@villasv  - Apologies for the latency on this. I'm going through our backlog and trying to sort out issues that need to be fixed in v0.8 versus ones that make more sense to integrate into the v0.9 branch. 

The tCaT vs tcat issue aside, can you confirm this works as intended now? I see we've added logic to ensure user-provided bucket names are all lowercase, but I want to verify that the signature aside, there's nothing outstanding here?

**Closed** 2019-07-22 19:27 UTC
